version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
