version: "3.7"
services:
  scrapy-jenkins-agent:
    build:
      context: scrapy-jenkins-agent
      dockerfile: Dockerfile
    image: tcsizmadia/scrapy-jenkins-agent
  jenkins:
    image: jenkins/jenkins:lts
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - 8081:8080
      - 50001:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
